import type { Job } from "@/types/job";

const BASE_URL = import.meta.env.VITE_BASE_URL;

// ======  get all jobs =======
export const fetchJobs = async (): Promise<Job[]> => {
  const res = await fetch(`${BASE_URL}/jobs`);

  if (!res.ok) {
    throw new Error("Failed to fetch jobs");
  }

  const data = await res.json();

  return data.data;
};

// type JobFilters = {
//   search?: string;
//   category?: string;
//   location?: string;
// };

// // get jobs with filters
// export const fetchJobs = async (filters?: JobFilters): Promise<Job[]> => {
//   const params = new URLSearchParams();

//   if (filters?.search) params.append("search", filters.search);

//   if (filters?.category) params.append("category", filters.category);

//   if (filters?.location) params.append("location", filters.location);

//   const res = await fetch(`${BASE_URL}/jobs?${params.toString()}`);

//   if (!res.ok) {
//     throw new Error("Failed to fetch jobs");
//   }

//   const data = await res.json();
//   return data.data;
// };




// get single job
export const fetchJobById = async (id: string): Promise<Job> => {
  const res = await fetch(`${BASE_URL}/jobs/${id}`);

  if (!res.ok) {
    throw new Error("Job not found");
  }

  const data = await res.json();

  return data.data;
};




// create jobs
// ( except id, created_at case they will automatically generated by backend api )
export const createJob = async (
  job: Omit<Job, "id" | "created_at" | "updated_at">,
): Promise<Job> => {
  const res = await fetch(`${BASE_URL}/jobs`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(job),
  });

  if (!res.ok) throw new Error("Failed to create job");

  const json = await res.json();
  return json.data;
};



// delete api
export const deleteJob = async (id: number | string) => {
  const res = await fetch(`${BASE_URL}/jobs/${id}`, {
    method: "DELETE",
  });

  if (!res.ok) {
    throw new Error("Failed to delete job");
  }

  const data = await res.json();
  return data.data;
};
